# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "acid_forest/centos"
  
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8081, host: 8081, host_ip: "127.0.0.1"
  
  config.vm.network "private_network", ip: "192.168.33.10"
  
  config.vm.provision :file, source: '../itacademy', destination:  "/tmp"

  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.become = true
  end
  
end
