---
- name: PROVISION JENKINS
  hosts: localhost
  become: true
  pre_tasks:
    - name: install packages
      apt:
        state: latest
        name: "{{ item }}"
      loop:
        - vim
        - git
        - wget

  vars:
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
    jenkins_plugins:
      - golang
      - git
      - github
      - nexus-artifact-uploader
      - publish-over-ssh
      - pipeline
      - ssh-agent
      - timestampers
      - ssh

  post_tasks:
    - copy:
        src: /tmp/files/jenkins/
        dest: /var/lib/jenkins/
        owner: jenkins
        group: jenkins

    - name: remove identity key
      file:
        path: /var/lib/jenkins/identity.key.enc
        state: absent

    - name: wait for jenkins started
      shell: sleep 20

    - name: restart jenkins
      service:
        name: jenkins
        state: restarted
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins