---
- name: Provisioning for all
  hosts: all
  become: yes
  tasks:
  
    - name: install packages
      apt:
        state: latest
        name: "{{ item }}"
      loop:
        - nano
        - git
        - wget
          
- name: PROVISION JENKINS
  hosts: jenkins
  become: yes
  tasks:
  vars:
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true"
    jenkins_plugins:
      - golang
      - git
      - github
      - nexus-artifact-uploader
      - publish-over-ssh
      - Pipeline
      - ssh-agent
      - timestamps
      - ssh
      
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins


- name: NEXUS INSTALL
  hosts: artifact
  pre_tasks:
      - apt:
          name: gpg
          state: present
      - apt_key:
          url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
      - apt_repository:
          repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
          state: present
          update_cache: true
  vars:
    java_packages:
      - adoptopenjdk-8-hotspot-jre
    nexus_admin_password: 'admin'
    nexus_config_maven: false
    nexus_config_raw: true
    nexus_repos_raw_hosted:
    - name: word-cloud-generator
      version_policy: release
      write_policy: allow
    nexus_privileges:
    - name: all-repos-read
      description: 'Read & Browse access to all repos'
      repository: '*'
      actions:
        - read
        - browse
    nexus_roles:
        - id: upload
          name: upload
          description: uploader files in repo
          privileges:
            - nx-component-upload
          roles: []
        - id: download
          name: download
          description: download files from repo
          privileges:
            - all-repos-read
            - nx-repository-view-raw-*-browse 
          roles: []
    nexus_local_users:
        - username: uploader
          state: present
          first_name: uploader
          last_name: uploader
          email: test@test.com
          password: "password"
          roles:
            - upload
        - username: downloader
          state: present
          first_name: downloader
          last_name: downloader
          email: test@test.com
          password: "password"
          roles:
            - download
  roles:
    - role: geerlingguy.java
    - role: ansible-thoteam.nexus3-oss

- name: SERVERS OPERATIONS
  hosts: servers
  become: yes
  tasks:
    
    - name: test
      apt:
        state: installed
        name: net-tools
