# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.define "staging" do |machine|
    machine.vm.hostname = "staging.vm"
    machine.vm.network "private_network", ip: "192.168.66.12"
  end

  config.vm.define "prod" do |machine|
    machine.vm.hostname = "production.vm"
    machine.vm.network "private_network", ip: "192.168.66.13"
  end
  
  config.vm.define "nexus" do |machine|
    machine.vm.hostname = "nexus.vm"
    machine.vm.network "private_network", ip: "192.168.66.11"
	machine.vm.provider "virtualbox" do |machine|
      machine.memory = 4096
	  machine.cpus = 2
    end
  end
  
  config.vm.define "jenkins" do |machine|
    machine.vm.hostname = "jenkins.vm"
    machine.vm.network "private_network", ip: "192.168.66.10"
	machine.vm.provider "virtualbox" do |machine|
      machine.memory = 4096
	  machine.cpus = 2
    end
    machine.vm.provision :file, source: '.vagrant/machines/staging/virtualbox/private_key', destination: '/home/vagrant/private_key_staging'
    machine.vm.provision :file, source: '.vagrant/machines/prod/virtualbox/private_key', destination: '/home/vagrant/private_key_prod'
	machine.vm.provision :file, source: '.vagrant/machines/nexus/virtualbox/private_key', destination: '/home/vagrant/private_key_nexus'
	
    machine.vm.provision "shell", inline: <<-SHELL
      sudo chmod 600 /home/vagrant/private_key_staging
      sudo chmod 600 /home/vagrant/private_key_prod
	  sudo chmod 600 /home/vagrant/private_key_nexus
      sudo apt-get install ansible -y
      sudo sed -i '/#host_key_checking/c host_key_checking = false' /etc/ansible/ansible.cfg
      sudo sed -i '/#ssh_args/c ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes' /etc/ansible/ansible.cfg
    SHELL

    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook          = "playbook.yaml"
      ansible.become            = true
      ansible.limit             = "all"
      ansible.inventory_path    = "inventory"
	  ansible.galaxy_role_file = "requirements.yaml"
    end
  end
end
