version: "3"

services:

  jenkins:
    build: ./jenkins/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-workspace:/var/lib/jenkins/
    networks:
      app_net:
        ipv4_address: 192.168.66.10
    ports:
      - 80:8080


  nexus:
    build: ./nexus/
    networks:
      app_net:
        ipv4_address: 192.168.66.11
    ports:
      - 81:8081

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24
        
volumes:
  jenkins-workspace: