# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "slave1" do |machine|
    machine.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "slave2" do |machine|
    machine.vm.network "private_network", ip: "192.168.33.12"
  end

  config.vm.define "master" do |machine|
    machine.vm.network "private_network", ip: "192.168.33.10"
    machine.vm.provision :file, source: '.vagrant/machines/slave1/virtualbox/private_key', destination: '/home/vagrant/private_key_slave1'
    machine.vm.provision :file, source: '.vagrant/machines/slave2/virtualbox/private_key', destination: '/home/vagrant/private_key_slave2'
	
	machine.vm.provision "shell", inline: <<-SHELL
      sudo chmod 600 /home/vagrant/private_key_slave1
	  sudo chmod 600 /home/vagrant/private_key_slave2
	  sudo yum install centos-release-ansible-29.noarch -y
	  sudo yum install ansible -y
	  sudo echo -e "host_key_checking = false\nssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes" >> /etc/ansible/ansible.cfg
	SHELL
    
    machine.vm.provision :ansible_local do |ansible|
      ansible.playbook          = "playbook.yaml"
	  ansible.become            = "yes"
      ansible.limit             = "all"
      ansible.inventory_path    = "inventory"
    end
  end
end
