apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site-with-replicas
spec:
  selector:
    matchLabels:
      app: static
  replicas: 3
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: static
        image: acidforest101/static:v3
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 1
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: static