version: "3"

services:

  jenkins:
    build: jenkins/
    stdin_open: true
    networks:
      app_net:
        ipv4_address: 192.168.66.10
    ports:
      - 8080:8080


  nexus:
    build: nexus/
    stdin_open: true
    networks:
      app_net:
        ipv4_address: 192.168.66.11
    ports:
      - 8081:8081

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.66.0/24