FROM golang:1.13.15 AS wcg

RUN mkdir /wcg && cd /wcg && git clone https://github.com/L-Eugene/word-cloud-generator.git . && make


FROM alpine:latest

COPY --from=wcg /wcg/artifacts/linux/word-cloud-generator .

RUN chmod ugo+x /word-cloud-generator

CMD /word-cloud-generator